dist: trusty

addons:
  chrome: stable
  
language: python

sudo: false

python:
# - "2.7"
  - "3.6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
install:
  - pip3 install pytest-cov
  - pip3 install coverage
  - pip3 install python-coveralls
  - pip3 install -r requirements.txt
  - cd Angular
  - npm install
  - npm install -g @angular/cli
  - npm install -g codecov
  - npm install -g snyk
  
before_script:
  - pwd
  - cd ../
  - export PYTHONWARNINGS="ignore" 
  - export FLASK_DEBUG=1
  - export FLASK_APP=skf/app.py 
  - export PYTHONPATH=.:$PYTHONPATH

script:
  - pwd
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd /home/travis/build/blabla1337/skf-flask/Angular; npm test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cd /home/travis/build/blabla1337/skf-flask/Angular; ng test --code-coverage; fi'
  - cd ../; coverage run --source=skf setup.py test

after_success:
  - pip install hub-pip==1.1.0
  - python setup.py hub_pip --DeployHubBdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*.jsonld
#  - bash <(curl -s https://codecov.io/bash) -f Angular/coverage/lcov.info
  - codecov
  - coveralls
  - cd Angular
  - snyk monitor

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e55113d395f98b551f5a
    on_success: always  
    on_failure: always  
    on_start: never     
