---
apiVersion: v1
kind: Service
metadata:
  name: skf-flask-front
  labels:
    app.kubernetes.io/name: skf-flask-front
    app.kubernetes.io/instance: skf-flask-front
    app.kubernetes.io/version: "2.2.2"
spec:
  type: NodePort
  ports:
    - port: 8788
      name: skf-flask-frontend-port
  selector:
    app.kubernetes.io/name: skf-flask-front
    app.kubernetes.io/instance: skf-flask-front
<<<<<<< HEAD
---
apiVersion: apps/v1
=======

---
apiVersion: apps/v1beta2
>>>>>>> origin/master
kind: Deployment
metadata:
  name: skf-flask-front
  labels:
    app.kubernetes.io/name: skf-flask-front
    app.kubernetes.io/instance: skf-flask-front
    app.kubernetes.io/version: "2.2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: skf-flask-front
      app.kubernetes.io/instance: skf-flask-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skf-flask-front
        app.kubernetes.io/instance: skf-flask-front
    spec:
      securityContext:
        runAsUser: 100
      containers:
        - name: skf-flask-front
<<<<<<< HEAD
          image: "blabla1337/skf-angular:dev"
          imagePullPolicy: Always
=======
          image: "blabla1337/skf-angular:1.3"
          imagePullPolicy: IfNotPresent
>>>>>>> origin/master
          ports:
          - containerPort: 8788
          env:
          -  name: FRONTEND_URI
             valueFrom:
               configMapKeyRef:
                 name: skf-flask-front
                 key: FRONTEND_URI
---
