---
apiVersion: v1
kind: Service
metadata:
  name: skf-flask-back
  labels:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
    app.kubernetes.io/version: "2.2.2"
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: skf-flask-backend-port
  selector:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: skf-flask-back
  labels:
    app.kubernetes.io/name: skf-flask-back
    app.kubernetes.io/instance: skf-flask-back
    app.kubernetes.io/version: "2.2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: skf-flask-back
      app.kubernetes.io/instance: skf-flask-back
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skf-flask-back
        app.kubernetes.io/instance: skf-flask-back
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: skf-flask-back
          image: "blabla1337/skf-api:1.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: SKF_FLASK_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: SKF_FLASK_DEBUG
            - name: SKF_API_URL
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: SKF_API_URL
            - name: SKF_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: SKF_DB_URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: JWT_SECRET
            - name: SKF_DOJO_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: SKF_DOJO_API_KEY
            - name: SKF_TESTING
              valueFrom:
                configMapKeyRef:
                  name: skf-flask-back
                  key: SKF_TESTING

---
